services:
  devhabit.api:
    build:
      target: dev
    volumes:
      - ./:/app
    environment:
      # те же переменные, что и в основном compose
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://devhabit.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - ASPNETCORE_ENVIRONMENT=Development

